# Generated by Django 5.0.1 on 2024-01-29 09:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_book_img'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='img',
            new_name='img_path',
        ),
    ]
